### Implementation of Global Sequence Aligment Technique to compare genetic sequences

In [1]:
from numpy import matrix

# Assign values


match = 3
transition_mismatch = 0
transversion_mismatch = -3
gap = -1

vertical_pointer = 'V '
horizontal_pointer = 'H '
diagonal_pointer = 'D '


In [2]:
def mismatches(a,b): #change to equal not minus
    if a == 1 and b==2 or a == 2 and b == 2:
        return transition_mismatch
    if a == 3 and b == 4 or a == 4 and b == 3:
        return transition_mismatch
    else:
        return transversion_mismatch

def check_match(a,b):

    values_dict = {
    'A': 1,
    'G': 2,
    'C': 3,
    'T': 4,
    }

    if a == b:
        return match
    elif a == '-' or b == '-':
        return gap
    else:
        l = values_dict[a]
        k = values_dict[b]
        return mismatches(l,k)


In [3]:
def pointers(diagonal_value,horizontal_value,vertical_value):
    pointer = max(diagonal_value,horizontal_value,vertical_value)
    if diagonal_value == pointer:
        if diagonal_value == horizontal_value:
            return 'DH'
        if diagonal_value == vertical_value:
            return 'DV'
        return diagonal_pointer
    elif horizontal_value == pointer:
        if horizontal_value == vertical_value:
            return 'VH'
        return horizontal_pointer
    elif vertical_value == pointer:
        return vertical_pointer

In [4]:

sequence1 = 'GAATACAGTTATGC'
sequence2 = 'GGATGCGTGATC'

s1_l = list(sequence1)
s2_l = list(sequence2)

GSAPlot = [[0 for x in range(len(s1_l)+1)] for y in range(len(s2_l)+1)]
PointerMatrix = [[0 for x in range(len(s1_l)+1)] for y in range(len(s2_l)+1)]

#First gaps will be filled
for i in range(len(s1_l)+1):
	GSAPlot[0][i] = GSAPlot[0][i]-i
for j in range(len(s2_l)+1):
	GSAPlot[j][0]= GSAPlot[j][0]-j

for i in range(1,len(s1_l)+1):
	PointerMatrix[0][i] = horizontal_pointer
for j in range(1,len(s2_l)+1):
	PointerMatrix[j][0]= vertical_pointer

In [5]:


for i in range(1,len(s1_l)+1):
    for j in range(1,len(s2_l)+1):
        diagonal_value = GSAPlot[j-1][i-1] + check_match(s1_l[i-1],s2_l[j-1])
        horizontal_value = GSAPlot[j][i-1] + gap
        vertical_value = GSAPlot[j-1][i] + gap
        GSAPlot[j][i] = max(diagonal_value,horizontal_value,vertical_value)

        PointerMatrix[j][i] = pointers(diagonal_value,horizontal_value,vertical_value)


In [6]:
gsa = matrix(GSAPlot)
pm = matrix(PointerMatrix)

print('The global aligment sequence matrix is: \n', gsa,'\n')
print('The pointer matrix is: \n',pm)


The global aligment sequence matrix is: 
 [[  0  -1  -2  -3  -4  -5  -6  -7  -8  -9 -10 -11 -12 -13 -14]
 [ -1   3   2   1   0  -1  -2  -3  -4  -5  -6  -7  -8  -9 -10]
 [ -2   2   3   2   1   0  -1  -2   0  -1  -2  -3  -4  -5  -6]
 [ -3   1   5   6   5   4   3   2   1   0  -1   1   0  -1  -2]
 [ -4   0   4   5   9   8   7   6   5   4   3   2   4   3   2]
 [ -5  -1   3   4   8   9   8   7   9   8   7   6   5   7   6]
 [ -6  -2   2   3   7   8  12  11  10   9   8   7   6   6  10]
 [ -7  -3   1   2   6   7  11  12  14  13  12  11  10   9   9]
 [ -8  -4   0   1   5   6  10  11  13  17  16  15  14  13  12]
 [ -9  -5  -1   0   4   5   9  10  14  16  15  16  15  17  16]
 [-10  -6  -2   2   3   7   8  12  13  15  14  18  17  16  15]
 [-11  -7  -3   1   5   6   7  11  12  16  18  17  21  20  19]
 [-12  -8  -4   0   4   5   9  10  11  15  17  16  20  19  23]] 

The pointer matrix is: 
 [['0' 'H ' 'H ' 'H ' 'H ' 'H ' 'H ' 'H ' 'H ' 'H ' 'H ' 'H ' 'H ' 'H '
  'H ']
 ['V ' 'D ' 'H ' 'H ' 'H ' 'H ' 